---
- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        # Path updated for user 'aarav' with hidden .jenkins directory
        src: "/home/aarav/.jenkins/workspace/2023MavenWebAppPipelineWithAnsible/target/2023MavenWebAppPipelineWithAnsible.war"
        dest: "/opt/tomcat/webapps/2023MavenWebAppPipelineWithAnsible.war"
        remote_src: no
    - name: Restart Tomcat
      systemd:
        name: tomcat
        shell: |
          /opt/tomcat/bin/shutdown.sh
          sleep 5
          /opt/tomcat/bin/startup.sh
        

